apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-lab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-lab
  template:
    metadata:
      labels:
        app: devops-lab
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: app
        image: ghcr.io/tekne-ops/devops-lab:latest
        ports:
        - containerPort: 5000
